protection:
  # Require pull request reviews before merging
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    dismissal_restrictions:
      users: []
      teams: []

  # Require status checks to pass before merging
  required_status_checks:
    strict: true
    contexts:
      - 'build-and-test'
      - 'deploy'

  # Include administrators
  enforce_admins: true

  # Restrict who can push to the protected branch
  restrictions:
    users: []
    teams: []
    apps: []
